on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: windows-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: nt8.unoeuro.com      # Angiv din serveradresse her
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/

    - name: Setup Simply Web Deploy
      uses: rasmusbuchholdt/simply-web-deploy@2.1.0
      with: 
          server-computer-name: https://nt8.unoeuro.com:8172/MsDeploy.axd
         


