// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skal_vi_videre.Models;

public partial class Company
{
    public int Id { get; set; }

    public string Cvr { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public string Role { get; set; }

    public string Description { get; set; }

    public int EventId { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}