// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skal_vi_videre.Models;

public partial class Event
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Genre { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string Location { get; set; }

    public int CompanyId { get; set; }

    public virtual ICollection<Company> Companies { get; set; } = new List<Company>();

    public virtual Company Company { get; set; }
}